/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Modelo.Usuario;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import Controlador.ControlarUsuario;



/**
 *
 * @author User
 */

public class FRMUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public FRMUsuario() {
        initComponents();
        TXTIdUsuario.setValue(0);
        TXTIdUsuario.setVisible(false);
        limpiarFormulario();
        
    }
    private void limpiarFormulario() {
        TXTIdUsuario.setValue(0);
        TXTNombreUsuario.setText("Nombre");
        TXTDocumetoUsuario.setText("documento");
        TXTCorreoUsuario.setText("Correo");
        TXTTelefonoUsuario.setText("telefono");
        TXTRolUsuario.setText("Rol");
        TXTBuqueda.setText("Escribe Busqueda");
        BTNModificar.setEnabled(false);
        BTNEliminar.setEnabled(false);
        llenarTabla();
    }
    
    public void llenarTabla() {
        Usuario unUsuario = new Usuario();
        DefaultTableModel tabla = (DefaultTableModel) TBLUsuario.getModel();
        Iterator<Usuario> itUsuario = unUsuario.Listar();
        Object[] filaUsuario = new Object[TBLUsuario.getColumnCount()];
        tabla.setRowCount(0);
        while (itUsuario.hasNext()) {
            unUsuario = itUsuario.next();
            filaUsuario[0] = unUsuario.getIdUSuario();
            filaUsuario[1] = unUsuario.getUsuarioNombre();
            filaUsuario[2] = unUsuario.getUsuarioTelefono();
            filaUsuario[3] = unUsuario.getUsuarioDocumento();
            filaUsuario[4] = unUsuario.getUsuarioCorreo();
            filaUsuario[5] = unUsuario.getUsuarioRol();
            tabla.addRow(filaUsuario);

        }
}

    private Usuario ObtenerUsuario() {

        Usuario elUsuario = new Usuario();
        elUsuario.setIdUSuario((Integer) TXTIdUsuario.getValue());
        elUsuario.setUsuarioNombre((String) TXTNombreUsuario.getText());
        elUsuario.setUsuarioTelefono((String) TXTTelefonoUsuario.getText());
        elUsuario.setUsuarioDocumento ((String) TXTDocumetoUsuario.getText());
        elUsuario.setUsuarioCorreo((String)TXTCorreoUsuario.getText());
        elUsuario.setUsuarioRol((String)TXTRolUsuario.getText());
       
        return elUsuario;
    }
    private void llenarTablaconBusqueda(String busqueda) {
        Usuario unUsuario = new Usuario();
        DefaultTableModel tabla = (DefaultTableModel) TBLUsuario.getModel();
        Iterator<Usuario> itUsuario = unUsuario.buscar(busqueda);
        Object[] filaUsuario = new Object[TBLUsuario.getColumnCount()];
        tabla.setRowCount(0);
        while (itUsuario.hasNext()) {
            unUsuario = itUsuario.next();
            filaUsuario[0] = unUsuario.getIdUSuario();
            filaUsuario[1] = unUsuario.getUsuarioNombre();
            filaUsuario[2] = unUsuario.getUsuarioTelefono();
            System.err.println("pasa por aca");
            filaUsuario[3] = unUsuario.getUsuarioCorreo();
            filaUsuario[4] = unUsuario.getUsuarioDocumento();
            filaUsuario[5] = unUsuario.getUsuarioRol();
            ((DefaultTableModel) TBLUsuario.getModel()).addRow(filaUsuario);

        }
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        TXTNombreUsuario = new javax.swing.JTextField();
        TXTIdUsuario = new javax.swing.JFormattedTextField();
        documento = new javax.swing.JLabel();
        TXTDocumetoUsuario = new javax.swing.JTextField();
        direccion = new javax.swing.JLabel();
        TXTCorreoUsuario = new javax.swing.JTextField();
        Celular = new javax.swing.JLabel();
        TXTTelefonoUsuario = new javax.swing.JTextField();
        rol = new javax.swing.JLabel();
        TXTRolUsuario = new javax.swing.JTextField();
        buscarlbl = new javax.swing.JLabel();
        TXTBuqueda = new javax.swing.JTextField();
        BTNInsertar = new javax.swing.JButton();
        BTNModificar = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        BTNcerrar = new javax.swing.JButton();
        BTNBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBLUsuario = new javax.swing.JTable();

        nombre.setText("Nombre");

        TXTNombreUsuario.setText("escribe nombre");
        TXTNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombreUsuarioActionPerformed(evt);
            }
        });

        TXTIdUsuario.setText("0");
        TXTIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIdUsuarioActionPerformed(evt);
            }
        });

        documento.setText("Ingrese  Documento");

        TXTDocumetoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDocumetoUsuarioActionPerformed(evt);
            }
        });

        direccion.setText("Correo");

        TXTCorreoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCorreoUsuarioActionPerformed(evt);
            }
        });

        Celular.setText("Ingrese telefono ");

        TXTTelefonoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTelefonoUsuarioActionPerformed(evt);
            }
        });

        rol.setText("Rol");

        TXTRolUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTRolUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTRolUsuarioFocusLost(evt);
            }
        });
        TXTRolUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRolUsuarioActionPerformed(evt);
            }
        });

        buscarlbl.setText("Buscar Usuario");

        TXTBuqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuquedaFocusLost(evt);
            }
        });
        TXTBuqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBuquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(TXTIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(documento)
                            .addComponent(direccion)
                            .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarlbl))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTCorreoUsuario)
                            .addComponent(TXTDocumetoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(TXTTelefonoUsuario)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TXTRolUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(TXTBuqueda, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXTIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(documento)
                    .addComponent(TXTDocumetoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion)
                    .addComponent(TXTCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarlbl)
                    .addComponent(TXTBuqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        BTNInsertar.setText("Insertar");
        BTNInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsertarActionPerformed(evt);
            }
        });

        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });

        BTNEliminar.setText("Eliminar");
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        BTNcerrar.setText("Cerrar");
        BTNcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcerrarActionPerformed(evt);
            }
        });

        BTNBuscar.setText("Buscar");
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });

        TBLUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre ", "Documento", "Telefono", "Correo", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBLUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BTNModificar)
                                .addComponent(BTNInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTNEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTNBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTNcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(BTNInsertar)
                    .addGap(15, 15, 15)
                    .addComponent(BTNModificar)
                    .addGap(18, 18, 18)
                    .addComponent(BTNEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(BTNcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(BTNBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombreUsuarioActionPerformed

    private void TXTDocumetoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDocumetoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDocumetoUsuarioActionPerformed

    private void TXTTelefonoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTelefonoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTelefonoUsuarioActionPerformed

    private void BTNInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsertarActionPerformed
        ControlarUsuario.controlarAccion(evt, ObtenerUsuario());
        limpiarFormulario();
    }//GEN-LAST:event_BTNInsertarActionPerformed

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
        ControlarUsuario.controlarAccion(evt, ObtenerUsuario());
        limpiarFormulario();
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
        ControlarUsuario.controlarAccion(evt, ObtenerUsuario());
        limpiarFormulario();
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void BTNcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcerrarActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_BTNcerrarActionPerformed

    private void TBLUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLUsuarioMouseClicked
        if (evt.getClickCount() == 1) {
            int fila = TBLUsuario.rowAtPoint(evt.getPoint());
            if (fila > -1) {
                TXTIdUsuario.setValue((Integer) TBLUsuario.getValueAt(fila, 0));
                TXTNombreUsuario.setText((String) TBLUsuario.getValueAt(fila, 1));
                TXTTelefonoUsuario.setText((String) TBLUsuario.getValueAt(fila, 2));
                TXTCorreoUsuario.setText((String) TBLUsuario.getValueAt(fila, 4));
                TXTDocumetoUsuario.setText((String) TBLUsuario.getValueAt(fila, 3));
                TXTRolUsuario.setText((String)TBLUsuario.getValueAt(fila, 5));
                BTNModificar.setEnabled(true);
                BTNEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_TBLUsuarioMouseClicked

    
    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        System.out.println("valor "+TXTBuqueda.getText());
        llenarTablaconBusqueda(TXTBuqueda.getText());
        
    }//GEN-LAST:event_BTNBuscarActionPerformed

    private void TXTCorreoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCorreoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCorreoUsuarioActionPerformed

    private void TXTRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRolUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRolUsuarioActionPerformed

    private void TXTRolUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTRolUsuarioFocusLost

    }//GEN-LAST:event_TXTRolUsuarioFocusLost

    private void TXTRolUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTRolUsuarioFocusGained
        if (TXTRolUsuario.getText().equals("Escriba texto a buscar")) {
            TXTRolUsuario.setText("");
        }
    }//GEN-LAST:event_TXTRolUsuarioFocusGained

    private void TXTIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIdUsuarioActionPerformed

    private void TXTBuquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuquedaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTBuquedaFocusGained

    private void TXTBuquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuquedaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTBuquedaFocusLost

    private void TXTBuquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBuquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTBuquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNInsertar;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JButton BTNcerrar;
    private javax.swing.JLabel Celular;
    private javax.swing.JTable TBLUsuario;
    private javax.swing.JTextField TXTBuqueda;
    private javax.swing.JTextField TXTCorreoUsuario;
    private javax.swing.JTextField TXTDocumetoUsuario;
    private javax.swing.JFormattedTextField TXTIdUsuario;
    private javax.swing.JTextField TXTNombreUsuario;
    private javax.swing.JTextField TXTRolUsuario;
    private javax.swing.JTextField TXTTelefonoUsuario;
    private javax.swing.JLabel buscarlbl;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel documento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel rol;
    // End of variables declaration//GEN-END:variables
}
