/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;
import Modelo.ConectarBD;
import java.beans.PropertyVetoException;

/**
 *
 * @author User
 */
public class MDIInicio extends javax.swing.JFrame {
    
    
    FRMDetalle FDetalle;
    FRMProductos Fproductos;
    FRMUsuario FUsuario;
    
   
    

    /**
     * Creates new form MDIProducto
     */
    public MDIInicio() {
        ConectarBD.getInstance();
        initComponents();
        FDetalle = new FRMDetalle();
        ESCCategoria.add(FDetalle);
        Fproductos = new FRMProductos();
        ESCCategoria.add(Fproductos);
        FUsuario = new FRMUsuario();
        ESCCategoria.add(FUsuario);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESCCategoria = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        MenuCategoria = new javax.swing.JMenu();
        ITEMMedias = new javax.swing.JMenuItem();
        SalirITEM = new javax.swing.JMenuItem();
        ITEMAdmin = new javax.swing.JMenuItem();
        UsuarioItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 48)); // NOI18N
        jLabel1.setText("       BIENVENIDO A CR7STORE");
        ESCCategoria.add(jLabel1);
        jLabel1.setBounds(160, 150, 670, 180);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ESCCategoria.add(jPanel2);
        jPanel2.setBounds(200, 170, 260, 0);

        MenuCategoria.setMnemonic('f');
        MenuCategoria.setText("Categorias");

        ITEMMedias.setMnemonic('a');
        ITEMMedias.setText("Cliente");
        ITEMMedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMMediasActionPerformed(evt);
            }
        });
        MenuCategoria.add(ITEMMedias);

        SalirITEM.setMnemonic('x');
        SalirITEM.setText("Salir");
        SalirITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirITEMActionPerformed(evt);
            }
        });
        MenuCategoria.add(SalirITEM);

        ITEMAdmin.setText("Admin");
        ITEMAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMAdminActionPerformed(evt);
            }
        });
        MenuCategoria.add(ITEMAdmin);

        UsuarioItem.setText("Usuario");
        UsuarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioItemActionPerformed(evt);
            }
        });
        MenuCategoria.add(UsuarioItem);

        menuBar.add(MenuCategoria);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ESCCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ESCCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirITEMActionPerformed
        ConectarBD.desconectar();
        try {
            FDetalle.setClosed(true);
            Fproductos.setClosed(true);
            FUsuario.setClosable(true);

        }
        catch (PropertyVetoException ex) {
            System.err.println("error al salir" + ex.getMessage());
        }
        System.exit(0);
    }//GEN-LAST:event_SalirITEMActionPerformed

    private void ITEMMediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMMediasActionPerformed
        FDetalle.setVisible(true);

    }//GEN-LAST:event_ITEMMediasActionPerformed

    private void ITEMAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMAdminActionPerformed
        Fproductos.setVisible(true);
    }//GEN-LAST:event_ITEMAdminActionPerformed

    private void UsuarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioItemActionPerformed
        FUsuario.setVisible(true);
    }//GEN-LAST:event_UsuarioItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MDIInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane ESCCategoria;
    private javax.swing.JMenuItem ITEMAdmin;
    private javax.swing.JMenuItem ITEMMedias;
    private javax.swing.JMenu MenuCategoria;
    private javax.swing.JMenuItem SalirITEM;
    private javax.swing.JMenuItem UsuarioItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
